[hypervisor.qemu]
path = "/opt/kata/bin/qemu-system-x86_64"

kernel = "/opt/kata/share/kata-containers/vmlinux.container"
image = "/opt/kata/share/kata-containers/kata-containers.img"

enable_iommu = true

virtio_fs_daemon = "/opt/kata/bin/virtiofsd"

default_vcpus = 1
default_memory = 2048
disable_block_device_use = false

machine_accelerators = ""
cpu_features = "pmu=off"

[factory]
template_path = "/run/vc/vm/template"
vm_cache_number = 0
vm_cache_endpoint = "/var/run/kata-containers/cache.sock"

[runtime]
internetworking_model="tcfilter"
disable_new_netns=false
sandbox_cgroup_only=false
static_sandbox_resource_mgmt=false
enable_cpu_memory_hotplug=false